# NOTE:
#     dBBBBBBb  dBP.dBBBBP   dBBBP
#      '   dB'     BP
#   dB'dB'dB' dBP  `BBBBb  dBBP
#  dB'dB'dB' dBP      dBP dBP
# dB'dB'dB' dBP  dBBBBP' dBBBBP
[tools]
age = "latest"
air = "latest"
ast-grep = "latest"
bitwarden = "latest"
bat = "latest"
bun = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
delta = "latest"
deno = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
go = "latest"
gofumpt = "latest"
gotestsum = "latest"
gum = "latest"
harper-ls = "latest"
jujutsu = "latest"
jq = "latest"
just = "latest"
lazydocker = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
protobuf = "latest"
python = "latest"
ripgrep = "latest"
ruff = "latest"
{{ if ne .chezmoi.os "windows" -}}
rust = { version = "nightly", components = "clippy,llvm-tools,rust-analyzer,rust-src" }
{{ end -}}
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
tinymist = "latest"
tlrc = "latest"
tokei = "latest"
tree-sitter = "latest"
typst = "latest"
typstyle = "latest"
usage = "latest"
uv = "latest"
vhs = "latest"
xh = "latest"
yazi = "latest"
yq = "latest"
yt-dlp = "latest"
zig = "latest"
zls = "latest"
zoxide = "latest"
"cargo:bacon" = "latest"
"cargo:bacon-ls" = "latest"
"cargo:cargo-cache" = "latest"
"cargo:cargo-update" = "latest"
"cargo:shellharden" = "latest"
"cargo:tlrc" = "latest"
{{ if ne .chezmoi.os "darwin" -}}
"cargo:kondo" = "latest"
{{ end -}}
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/incu6us/goimports-reviser/v3" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:github.com/fatih/gomodifytags" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/josharian/impl" = "latest"
"go:github.com/wader/jq-lsp" = "latest"
{{- if eq .chezmoi.os "darwin" }}
"github:joncrangle/podapple" = "latest"
"pipx:waybarrios/vllm-mlx" = "latest"
{{- end }}
{{- if eq .chezmoi.os "windows" }}
"go:github.com/joncrangle/teams-green" = "latest"
"npm:n8n" = "latest"
{{- end }}
{{- if ne .chezmoi.os "windows" }}
"cargo:skim" = "latest"
{{- end }}
"github:Feel-ix-343/markdown-oxide" = "latest"
"go:github.com/a-h/templ/cmd/templ" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:btca" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:@microsoft/compose-language-service" = "latest"
"npm:live-server" = "latest"
"npm:markdown-toc" = "latest"
"npm:@mdx-js/language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:opencode-ai" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:qmk" = { version = "latest" }
"pipx:sqlfluff" = { version = "latest" }
"pipx:sqlit-tui" = { version = "latest", extras = "libsql,mariadb,postgres" }
"pipx:ty" = { version = "latest" }

[settings]
experimental = true
locked = false
npm.package_manager = "bun"
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python", "rust"]
