[misc]
# pre_sudo = true
disable = [
{{- if ne .chezmoi.os "linux" -}}
    "system", 
{{- end -}}
{{- if eq .chezmoi.os "windows" -}}
    "rustup", 
{{- end -}}
    "containers","mas","vim","chocolatey","winget","microsoft_store"]
set_title = false
cleanup = true
skip_notify = true
no_self_update = true


[brew]
greedy_cask = true
autoremove = true


[linux]
arch_package_manager = "paru"


[git]
# Additional git repositories to pull
{{- if eq .chezmoi.os "darwin" }}
 repos = [ "~/Documents/Code/*/" ]
{{- end -}}
{{- if eq .chezmoi.os "linux" }}
 repos = [ "~/Code/*/" ]
{{- end -}}
{{- if eq .chezmoi.os "windows" }}
 repos = [ "~\\Downloads\\Code\\*\\" ]
{{- end }}


[windows]
self_rename = true


[mise]
bump = false
jobs = 4
interactive = false
